#Expyriment 0.9.0 (Python 3.6.3), .xpe-file, coding: UTF-8
#date: Thu Mar 22 2018 10:17:49
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='is153352', release='4.9.8-040908-generic', version='#201702040431 SMP Sat Feb 4 09:32:59 UTC 2017', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
265,Picture,loaded,b'pictures/imag10.png'
272,Picture,loaded,b'pictures/imag10.png'
275,stderr,received,'Traceback (most recent call last):'
275,stderr,received,'  File "audiovis.py", line 59, in <module>'
276,stderr,received,"    events.put((onset, 'picture', f, mappicture[f]))"
276,stderr,received,"NameError: name 'mappicture' is not defined"
