#Expyriment 0.9.0 (Python 3.6.3), .xpe-file, coding: UTF-8
#date: Thu Mar 22 2018 10:13:18
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='is153352', release='4.9.8-040908-generic', version='#201702040431 SMP Sat Feb 4 09:32:59 UTC 2017', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
986,design,log,
#design: #exp: First Experiment
#design: block_cnt,block_id,trial_cnt,trial_id
987,design,logged,
987,Experiment,started
987,stderr,received,'Traceback (most recent call last):'
987,stderr,received,'  File "audiovis.py", line 80, in <module>'
987,stderr,received,'    if a.time > onset:'
987,stderr,received,"TypeError: '>' not supported between instances of 'int' and 'str'"
